### ISSUE TITLE
pythonでsotaやslackと連携できる最小構成システムを作る

### ISSUE THREAD

**Issue by garicchi** [tis-intern-apparel/ApparelStrategy#1]
developブランチでsotaと接続 : 本番用
masterブランチでslackと接続 : テスト用

環境変数を指定している部分があるけどめんどくさいのでコードに埋め込むかファイルから読み込むようにしてほしい

**Comment by garicchi** [comment]
add assignees

**Comment by Hsjk** [comment]
既存のシステムから、ホットペッパーのAPIを利用した対話を省きました。
ただ、システムを動かすには、ホットペッパーのAPIキーの入力がまだ必要なので注意です。
